### ISSUE TITLE
build error on windows 10: make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal' 

### ISSUE THREAD

**Issue by yingfei** [facebook/folly#1324]
recent versions, 
build error with visual studio 2019 , or vcpkg,    windows 10.

```
 D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1644): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1669): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1669): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1721): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1721): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
```

**Comment by Orvid** [comment]
This is a bug with MSVC 2019 that is already fixed in the preview build if I remember correctly, though the preview build breaks in a different way so that's not great :(

**Comment by dimarusyy** [comment]
The issue is still there.
```
D:\dev\vcpkg\buildtrees\folly\src\head\master-40c5e14eb6\folly/lang/Pretty.h(89): warning C4686: 'folly::detail::pretty_carray_from': possible change in behavior, change in UDT return calling convention
D:\dev\vcpkg\buildtrees\folly\src\head\master-40c5e14eb6\folly/SharedMutex.h(1644): error C2672: 'operator __surrogate_func': no matching overloaded function found
```

Any chance to use std;:atomic_ref instead of mimic implementation in AtomicRef.h ?

Also, regarding the code :
```
    uint32_t slot = make_atomic_ref(tls_lastDeferredReaderSlot)
                        .load(std::memory_order_relaxed);
```
```
  atomic_ref<T> operator()(T& ref) const {
    return atomic_ref<T>{ref};
  }
```
Why not simply to use `std::atomic<std::reference_wrapper<T>>` ?

**Comment by chllcy** [comment]
VS2019 and windows 10
vcpkg install folly:x64-windows --head
how can fix this problem?
the folly version:"url": "https://api.github.com/repos/facebook/folly/git/commits/0938cf4150a97143125ac892303a90cef7ad2254"

-----------------------------------------------------------------------------------------
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/lang/Pretty.h(89): warning C4686: 'folly::detail::pretty_carray_from': possible change in behavior, change in UDT return calling convention
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1644): error C2672: 'operator __surrogate_func': no matching overloaded function found

D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(404): note: while compiling class template member function 'void folly::SharedMutexImpl<false,void,std::atomic,false,false>::lock_shared(folly::SharedMutexImpl<false,void,std::atomic,false,false>::Token &)'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1340): note: see reference to function template instantiation 'void folly::SharedMutexImpl<false,void,std::atomic,false,false>::lock_shared(folly::SharedMutexImpl<false,void,std::atomic,false,false>::Token &)' being compiled
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1549): note: see reference to class template instantiation 'folly::SharedMutexImpl<false,void,std::atomic,false,false>' being compiled
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1644): error C2783: 'folly::atomic_ref folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1669): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1669): error C2783: 'folly::atomic_ref folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1721): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1721): error C2783: 'folly::atomic_ref folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'

**Comment by yfeldblum** [comment]
Closing due to age.
