### ISSUE TITLE
When will folly support VS ?

### ISSUE THREAD

**Issue by pengweichu** [facebook/folly#529]
Hello, I really would like to use folly in my project, when will it support Windows ?

Thanks

**Comment by Orvid** [comment]
The most definitive answer I can give currently is: soon. I've been working on getting Folly building and functional on Windows for quite a while now, and have things working, it's just the build process that's currently blocking. I have it building locally, I just have to make it so that everyone else can build it.

**Comment by pengweichu** [comment]
@Orvid thanks for update and thanks for your works!

**Comment by gogowishfly** [comment]
Great！

**Comment by sunwangme** [comment]
great

**Comment by KindDragon** [comment]
You can not try folly from [`vcpkg`](https://github.com/Microsoft/vcpkg), just run command `folly:x64-windows`
Related #405, #54

**Comment by spartucus** [comment]
Great! 
It will be better if we can build folly from source on Windows.

**Comment by KindDragon** [comment]
You can do this too, but you need to install before: zlib, openssl, boost, libevent, double-conversion, glog, gflags, lz4, liblzma, snappy

**Comment by PhoebeHui** [comment]
any updates for this?

**Comment by KindDragon** [comment]
You can build it for Windows

**Comment by PhoebeHui** [comment]
Thank you KindDragon!

Could you share the steps for building it with MSVC on Windows? or some instructions?

I only get the source of the zlib, openssl, boost, libevent, double-conversion, glog, gflags, lz4, liblzma, snappy, it's hard to get all of them build & install successfully for me. Is there some setup scripts like OSQuery: https://github.com/facebook/osquery/blob/master/tools/make-win64-dev-env.bat, I have install some packages on C:\ProgramData\chocolatey\lib by execute the scripts, but I don't how to make that works with Folly.

**Comment by lazylazypig** [comment]
@KindDragon 
Hi,
I tested a very simple example about folly::Promise/Future on vs2015.  but when i include the header  "folly/futures/Future.h", i got errors as bellow:
Error	C2589	'(': illegal token on right side of '::'
Error	C2059	syntax error: '::
....

the errors locate at  file folly/detail/CacheLocality.h, line 267: 
static_assert(kMaxCpus - 1 <= std::numeric_limits<CompactStripe>::max(),
                "stripeByCpu element type isn't wide enough");

what's the ploblem and how to fix it? thanks

**Comment by KindDragon** [comment]
@lazylazypig  I compiled folly with VS2017

**Comment by lazylazypig** [comment]
@KindDragon thanks for your reply. when you build folly with VS2017, did you just use the command 'vcpkg install folly:x64-windows' or you build it from the latest source code from github? thanks

**Comment by KindDragon** [comment]
@lazylazypig Yes, 'vcpkg install folly:x64-windows'. 
`'vcpkg install folly:x64-windows --head' (latest master) failing for me with error:
```
folly-master\folly\experimental\logging\LogStreamProcessor.cpp(98): error C2039: 'category': is not a member of 'folly::XlogFileScopeInfo'
```
They often brake MSVC build.

**Comment by Orvid** [comment]
Which version of MSVC 2015 are you trying to build with. We do partially support VS 2015, but only with Update 3 installed. The builds do tend to break on master fairly often unfortunately :(

**Comment by KindDragon** [comment]
@lazylazypig I can compile tag `v2017.05.08.00` with MSVC2015U3

**Comment by Maktm** [comment]
@KindDragon Why is folly only supported on x64? Was this a design decision from the beginning and if so, why?

https://github.com/Microsoft/vcpkg/issues/1395#event-1151973004

**Comment by vslavik** [comment]
> Why is folly only supported on x64?

Ah, that's a shame *especially* on Windows. Confusing too, because there seem to be [relatively recent commits](https://github.com/facebook/folly/commit/0826d16bb14b477fa619a4a30f4d8c000f381ff4) that fix 32bit compilation... I too would love to know which parts this comes from, because I hoped to use folly's much-better futures instead of Boost.Thread's mess.

**Comment by KindDragon** [comment]
IDK, ask @Orvid

**Comment by Orvid** [comment]
The Windows port is 64-bit only by design. The socket's portability API relies on the fact that a `HANDLE` and an `int` are separately overloadable. That's not possible in 32-bit :( In theory there are parts of Folly that probably work on 32-bit Windows, but it's not tested at all.

There is part of Folly that is tested on 32-bit, but only on IOS and Android toolchains. The rest of Folly is tested exclusively on 64-bit platforms.

**Comment by JunielKatarn** [comment]
Hi. I'm trying to use folly futures on windows.
Is this possible at all?

The simplest CPP source:
```
#include <folly/futures/Future.h>
```
spits this compiler error due to ptrhead.h:
```
folly/MicroSpinLock.h(45): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
```

**Comment by yfeldblum** [comment]
@JunielKatarn - It looks like you have an old version of Folly - this particular `#include` was addressed in 37af03980d1e36c1417998d7df2edbf6f182f07a.

**Comment by JunielKatarn** [comment]
Got it. Thanks!

**Comment by Orvid** [comment]
Windows support is largely complete, with a few minor issues remaining, so I'm going to close this out :)
