### ISSUE TITLE
Folly build failed with MSVC on windows

### ISSUE THREAD

**Issue by PhoebeHui** [facebook/folly#802]
Folly build failed with MSVC on windows, there are 2 issues, could you help have a look?

Environment
VCPKG(latest revision from github) + Visual Studio 15.5.7  +   windows sever 2016

Repro steps:
1.	Open X64 native tools command prompt for VS2017
2.	git clone https://github.com/Microsoft/vcpkg  D:\VCPKG\src
3.	cd d:\vcpkg\src
4.	devenv /upgrade .\toolsrc\vcpkg.sln
5.	set _CL_=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
6.	msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion 10.0.16299.0  toolsrc\vcpkg.sln /t:Rebuild
7.	set _CL_=
8.	set path=%cd%\toolsrc\Release;%path%
9.	vcpkg install folly:x64-windows –head

Issue #1
d:\folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly\experimental\hazptr\hazptr-impl.h(316): error C2338: hazptr_priv must be trivial to avoid a branch to check initialization

Workaround : we consider it’s not safe to make the compiler change at this time, we comment out static_assert in line#316 in folly/experimental/hazptr/hazptr-impl.h.

issue #2
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(355): error C2668: 'folly::launder': ambiguous call to overloaded function
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/lang/Launder.h(46): note: could be 'T *folly::launder<Value>(T *) noexcept'
        with
        [
            T=std::string,
            Value=std::string
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\new(22): note: or       '_Ty *std::launder<Value>(_Ty *) noexcept' [found using argument-dependent lookup]
        with
        [
            _Ty=std::string,
            Value=std::string
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(355): note: while trying to match the argument list '(std::string *)'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(352): note: while compiling class template member function 'void folly::Optional<std::string>::StorageNonTriviallyDestructible::clear(void)'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(349): note: see reference to function template instantiation 'void folly::Optional<std::string>::StorageNonTriviallyDestructible::clear(void)' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(363): note: see reference to class template instantiation 'folly::Optional<std::string>::StorageNonTriviallyDestructible' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(395): note: see reference to class template instantiation 'folly::Optional<std::string>::Storage' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/experimental/ProgramOptions.h(73): note: see reference to class template instantiation 'folly::Optional<std::string>' being compiled

Possible fix: Add ‘folly::’ before launder in folly/Optional.h, there are 4 place need update in this file.

**Comment by yfeldblum** [comment]
Note: these should be separate issues.

Re (1), it is already fixed in master - the `static_assert` should pass for MSVC now.

**Comment by PhoebeHui** [comment]
Thanks KindDragon!

The below error still repro with latest Folly revision.
 D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(355): error C2668: 'folly::launder': ambiguous call to overloaded function
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/lang/Launder.h(46): note: could be 'T *folly::launder<Value>(T *) noexcept'
        with
        [
            T=folly::jsonschema::`anonymous-namespace'::SchemaError,
            Value=folly::jsonschema::`anonymous-namespace'::SchemaError
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\new(20): note: or       '_Ty *std::launder<Value>(_Ty *) noexcept' [found using argument-dependent lookup]
        with
        [
            _Ty=folly::jsonschema::`anonymous-namespace'::SchemaError,
            Value=folly::jsonschema::`anonymous-namespace'::SchemaError
        ]
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(355): note: while trying to match the argument list '(folly::jsonschema::`anonymous-namespace'::SchemaError *)'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(352): note: while compiling class template member function 'void folly::Optional<folly::jsonschema::`anonymous-namespace'::SchemaError>::StorageNonTriviallyDestructible::clear(void)'
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(349): note: see reference to function template instantiation 'void folly::Optional<folly::jsonschema::`anonymous-namespace'::SchemaError>::StorageNonTriviallyDestructible::clear(void)' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(363): note: see reference to class template instantiation 'folly::Optional<folly::jsonschema::`anonymous-namespace'::SchemaError>::StorageNonTriviallyDestructible' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Optional.h(395): note: see reference to class template instantiation 'folly::Optional<folly::jsonschema::`anonymous-namespace'::SchemaError>::Storage' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly\experimental\JSONSchema.cpp(77): note: see reference to class template instantiation 'folly::Optional<folly::jsonschema::`anonymous-namespace'::SchemaError>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\chrono(201): note: see reference to class template instantiation 'std::chrono::duration<__int64,std::nano>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\chrono(799): note: see reference to class template instantiation 'std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration>' being compiled
D:\Folly\vcpkg\src\buildtrees\folly\src\head\folly-master\folly/Range.h(1215): note: see reference to class template instantiation 'folly::Range<const char *>' being compiled

**Comment by Orvid** [comment]
It looks like you have a far newer version of the `<new>` header installed than the compiler you're trying to build with. MSVC version 14.12.25827 doesn't include support for `std::launder`. The newest preview doesn't either (though Folly is broken because of that as well because the nightlies did)

**Comment by Orvid** [comment]
I believe the current version of Folly correctly guards our std::launder implementation and shouldn't be an issue currently.

**Comment by PhoebeHui** [comment]
I checked the latest source, looks it doesn't fix, see https://github.com/facebook/folly/blob/master/folly/Optional.h#L355
https://github.com/facebook/folly/blob/master/folly/Optional.h#L370
https://github.com/facebook/folly/blob/master/folly/Optional.h#L377
https://github.com/facebook/folly/blob/master/folly/Optional.h#L386

**Comment by PhoebeHui** [comment]
Folly is clean in our testing, this issue should be fixed.
