### ISSUE TITLE
malloc madness

### ISSUE THREAD

**Issue by miramar-labs** [facebook/folly#838]
abandoned gcc 7.3.0 on RHEL7.4 and moved to Ubuntu 16.04 gcc 5.4.0
got further - folly built OK
however, when I tried building some code that *uses* folly, I ran into a compilation error. It seems that the declaration of malloc from libjemalloc-dev conflicts with the one in the std lib on the system:

`
In file included from /usr/local/include/folly/memory/Malloc.h:32:0,
                 from /usr/local/include/folly/FBString.h:60,
                 from /usr/local/include/folly/Demangle.h:19,
                 from /usr/local/include/folly/ExceptionWrapper.h:33,
                 from /usr/local/include/folly/Try.h:18,
                 from /usr/local/include/folly/futures/Future.h:31,
                 from /home/whacuser/clipper/src/libclipper/src/query_processor.cpp:16:
/usr/include/jemalloc/jemalloc.h:137:46: error: declaration of âvoid* malloc(size_t)â has a different exception specifier
 JEMALLOC_EXPORT void *je_malloc(size_t size) JEMALLOC_ATTR(malloc);
                                              ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/iomanip:40,
                 from /home/whacuser/clipper/src/libclipper/src/query_processor.cpp:3:
/usr/include/stdlib.h:466:14: error: from previous declaration âvoid* malloc(size_t) throw ()â
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
`

Q is there a trick or magic preprocessor flag that will resolve this?

**Comment by miramar-labs** [comment]
I found that removing the libjemalloc-dev package resolved this issue .. but there must be a better way?

**Comment by simpkins** [comment]
This is a bug in jemalloc that was fixed in jemalloc version 4+: https://github.com/jemalloc/jemalloc/issues/237

**Comment by liliarizona** [comment]
> This is a bug in jemalloc that was fixed in jemalloc version 4+: [jemalloc/jemalloc#237](https://github.com/jemalloc/jemalloc/issues/237)
`
If libjemalloc-dev is installed, I still see the error:
In file included from /usr/local/include/folly/logging/xlog.h:22:
In file included from /usr/local/include/folly/logging/LogStream.h:21:
In file included from /usr/local/include/folly/logging/LogCategory.h:25:
In file included from /usr/local/include/folly/Synchronized.h:32:
In file included from /usr/local/include/folly/SharedMutex.h:29:
In file included from /usr/local/include/folly/concurrency/CacheLocality.h:33:
In file included from /usr/local/include/folly/Memory.h:36:
In file included from /usr/local/include/folly/memory/Malloc.h:43:
/usr/local/include/folly/memory/detail/MallocImpl.h:27:7: error: exception specification in declaration does not match previous declaration
void* mallocx(size_t, int) __attribute__((__nothrow__, __weak__));
      ^
/usr/include/jemalloc/jemalloc.h:147:23: note: previous declaration is here
JEMALLOC_EXPORT void    *je_mallocx(size_t size, int flags);
                         ^
/usr/include/jemalloc/jemalloc.h:46:22: note: expanded from macro 'je_mallocx'
#  define je_mallocx mallocx
                     ^
`
