### ISSUE TITLE
MSVC compile issue with 15.8.2

### ISSUE THREAD

**Issue by michaelaeriksen** [facebook/folly#920]
```
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\algorithm(5386): error C2676: binary '<': 'const _Ty' does not define this operator or a conversion to a type acceptable to the predefined operator
1>        with
1>        [
1>            _Ty=std::chrono::duration<__int64,std::nano>
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\algorithm(5385): note: see reference to function template instantiation 'const _Ty &std::max<std::chrono::duration<__int64,std::nano>>(const _Ty &,const _Ty &) noexcept(<expr>)' being compiled
1>        with
1>        [
1>            _Ty=std::chrono::duration<__int64,std::nano>
1>        ]
1>e:\vcpkg-fox\installed\x64-windows\include\folly\detail\memoryidler.h(157): note: see reference to function template instantiation 'bool folly::detail::MemoryIdler::futexWaitPreIdle<std::atomic,Deadline,IdleTime>(folly::detail::FutexResult &,folly::detail::Futex<std::atomic> &,uint32_t,const Deadline &,uint32_t,IdleTime,size_t,float)' being compiled
1>        with
1>        [
1>            Deadline=std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration>,
1>            IdleTime=std::chrono::steady_clock::duration
1>        ]
1>e:\vcpkg-fox\installed\x64-windows\include\folly\synchronization\baton.h(301): note: see reference to function template instantiation 'folly::detail::FutexResult folly::detail::MemoryIdler::futexWaitUntil<std::atomic,std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration>,std::chrono::steady_clock::duration>(folly::detail::Futex<std::atomic> &,uint32_t,const Deadline &,uint32_t,const IdleTime &,size_t,float)' being compiled
1>        with
1>        [
1>            Deadline=std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration>,
1>            IdleTime=std::chrono::steady_clock::duration
1>        ]
1>e:\vcpkg-fox\installed\x64-windows\include\folly\synchronization\baton.h(176): note: see reference to function template instantiation 'bool folly::Baton<true,std::atomic>::tryWaitSlow<std::chrono::steady_clock,std::chrono::steady_clock::duration>(const std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration> &,const folly::WaitOptions &) noexcept' being compiled
1>e:\vcpkg-fox\installed\x64-windows\include\folly\synchronization\baton.h(176): note: see reference to function template instantiation 'bool folly::Baton<true,std::atomic>::tryWaitSlow<std::chrono::steady_clock,std::chrono::steady_clock::duration>(const std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration> &,const folly::WaitOptions &) noexcept' being compiled
1>e:\vcpkg-fox\installed\x64-windows\include\folly\synchronization\baton.h(170): note: while compiling class template member function 'void folly::Baton<true,std::atomic>::wait(const folly::WaitOptions &) noexcept'
1>e:\vcpkg-fox\installed\x64-windows\include\folly\defaultkeepaliveexecutor.h(46): note: see reference to function template instantiation 'void folly::Baton<true,std::atomic>::wait(const folly::WaitOptions &) noexcept' being compiled
1>e:\vcpkg-fox\installed\x64-windows\include\folly\defaultkeepaliveexecutor.h(145): note: see reference to class template instantiation 'folly::Baton<true,std::atomic>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\chrono(201): note: see reference to class template instantiation 'std::chrono::duration<__int64,std::nano>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\chrono(799): note: see reference to class template instantiation 'std::chrono::time_point<std::chrono::steady_clock,std::chrono::steady_clock::duration>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\algorithm(5386): error C2056: illegal expression
```

**Comment by michaelaeriksen** [comment]
I use 2018.08.27.00. The problem is in folly/folly/detail/MemoryIdler.h. It looks like it might be fixed yesterday, but compiling with --head fails with an error in FileUtils.

**Comment by ras0219-msft** [comment]
Ok, the latest in vcpkg appears to be 2018.07.30[1] so for now this doesn't look like a vcpkg issue (but we will need to address this while updating).

[1] https://github.com/Microsoft/vcpkg/blob/4b4aac037d99569864a4bf44f6f6902849232935/ports/folly/CONTROL

**Comment by Orvid** [comment]
Master is currently broken on Windows due to us missing that the windows build failed on a couple of changes that landed today.

The fix for the FileUtils error is in https://github.com/facebook/folly/commit/341c36d74e201a2811d9db31e2c3f845589081fa. 

I hope to land a fix for the invalid escape sequence error either later tonight or early tomorrow (PST). The fix is swapping the `\e` for `\033` in [folly/logging/CustomLogFormatter.cpp](https://github.com/facebook/folly/blob/master/folly/logging/CustomLogFormatter.cpp#L45), even though that entire mechanism needs to be shifted around to work properly for Windows without enabling any of the new console modes, which I don't really want to do from library code.

**Comment by Orvid** [comment]
I've not been able to reproduce the issue you're seeing locally, but, as-of https://github.com/facebook/folly/commit/35312df92d73335d330863f16a2315baf12404ca, the last known issue in master is now fixed.

**Comment by michaelaeriksen** [comment]
Compiling folly with --head now works, but I still have an issue with futexWaitUntil. 

```
  static FutexResult futexWaitUntil(
      Futex& fut,
      uint32_t expected,
      Deadline const& deadline,
      uint32_t waitMask = -1,
      IdleTime const& idleTimeout =
          defaultIdleTimeout.load(std::memory_order_acquire),
      size_t stackToRetain = kDefaultStackToRetain,
      float timeoutVariationFrac = 0.5) {
    FutexResult pre;
    assert(!"XXX COMPILE FIX WINDOWS");
    //if (futexWaitPreIdle(
    //        pre,
    //        fut,
    //        expected,
    //        deadline,
    //        waitMask,
    //        idleTimeout,
    //        stackToRetain,
    //        timeoutVariationFrac)) {
    //  return pre;
    //}

    using folly::detail::futexWaitUntil;
    return futexWaitUntil(&fut, expected, deadline, waitMask);
  }
```

I need to comment out the call to futexWaitPreIdle for anything to build. I'm using folly extensively in my project and I guess I'm hitting a code path that triggers this compile error.

**Comment by yfeldblum** [comment]
Is there a specific error message?
